spring:
  application:
    name: customer-profile-service
  datasource:  
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://34.73.150.120:3306/customer
#      url: jdbc:mysql://localhost:3006/customer
#      username: root
#      password: admin
      url: jdbc:postgresql://localhost:5432/panera
#      url: jdbc:postgresql://35.188.28.127:5432/panera
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect